t_s = {'cardiotocography_2and3_33_variant1.mat':[33, 40, 46, 53, 59, 66],
       'diabetes_tested_positive_26_variant1.mat':[26, 39, 81, 83, 91, 106],
       'ionosphere_b_24_variant1.mat':[24, 26, 31, 48, 52, 54],
       'pageblocks_1_258_variant1.mat':[258, 420, 781, 1348, 1404, 1476],
       'pima_TRUE_55_variant1.mat':[55, 86, 145, 165, 175, 180],
       'sonar_M_10_variant1.mat':[10, 12, 13, 14, 15, 18],
       'wbc_malignant_39_variant1.mat':[39, 48, 49, 50, 52, 54],
       'wdbc_M_39_variant1.mat':[39, 41, 42, 43, 45, 46],
       'yeast_ERL_5_variant1.mat':[5, 6, 7, 8, 9, 10],
        }

best_lambs = { 'cardiotocography_2and3_33_variant1.mat':[0.65],
               'diabetes_tested_positive_26_variant1.mat':[0.1, 0.2, 0.15],
               'ionosphere_b_24_variant1.mat':[0.25, 0.35, 0.65],
               'pageblocks_1_258_variant1.mat':[0.35, 0.4, 0.4],
               'pima_TRUE_55_variant1.mat':[0.05, 0.1, 0.15],
               'sonar_M_10_variant1.mat':[0.05, 0.1, 0.4],
               'wbc_malignant_39_variant1.mat':[0.05, 0.7, 0.1],
               'wdbc_M_39_variant1.mat':[0.05, 0.3, 0.15],
               'yeast_ERL_5_variant1.mat':[0.65, 0.65, 0.75],
                }


comparison_result_fnames = [
    'comparison\\cardiotocography_2and3_33_variant1_COF.mat',
    'comparison\\cardiotocography_2and3_33_variant1_COPOD.mat',
    'comparison\\cardiotocography_2and3_33_variant1_DCROD.mat',
    'comparison\\cardiotocography_2and3_33_variant1_DIS.mat',
    'comparison\\cardiotocography_2and3_33_variant1_ECOD.mat',
    'comparison\\cardiotocography_2and3_33_variant1_fastABOD.mat',
    'comparison\\cardiotocography_2and3_33_variant1_GrC.mat',
    'comparison\\cardiotocography_2and3_33_variant1_IE.mat',
    'comparison\\cardiotocography_2and3_33_variant1_IForest.mat',
    'comparison\\cardiotocography_2and3_33_variant1_INFLO.mat',
    'comparison\\cardiotocography_2and3_33_variant1_kNN.mat',
    'comparison\\cardiotocography_2and3_33_variant1_LDOF.mat',
    'comparison\\cardiotocography_2and3_33_variant1_LOF.mat',
    'comparison\\cardiotocography_2and3_33_variant1_LoOP.mat',
    'comparison\\cardiotocography_2and3_33_variant1_ODGrCR.mat',
    'comparison\\cardiotocography_2and3_33_variant1_ODIN.mat',
    'comparison\\cardiotocography_2and3_33_variant1_ROD.mat',
    'comparison\\cardiotocography_2and3_33_variant1_SEQ.mat',
    'comparison\\cardiotocography_2and3_33_variant1_WDOD.mat',

    'comparison\\diabetes_tested_positive_26_variant1_COF.mat',
    'comparison\\diabetes_tested_positive_26_variant1_COPOD.mat',
    'comparison\\diabetes_tested_positive_26_variant1_DCROD.mat',
    'comparison\\diabetes_tested_positive_26_variant1_DIS.mat',
    'comparison\\diabetes_tested_positive_26_variant1_ECOD.mat',
    'comparison\\diabetes_tested_positive_26_variant1_fastABOD.mat',
    'comparison\\diabetes_tested_positive_26_variant1_GrC.mat',
    'comparison\\diabetes_tested_positive_26_variant1_IE.mat',
    'comparison\\diabetes_tested_positive_26_variant1_IForest.mat',
    'comparison\\diabetes_tested_positive_26_variant1_INFLO.mat',
    'comparison\\diabetes_tested_positive_26_variant1_kNN.mat',
    'comparison\\diabetes_tested_positive_26_variant1_LDOF.mat',
    'comparison\\diabetes_tested_positive_26_variant1_LOF.mat',
    'comparison\\diabetes_tested_positive_26_variant1_LoOP.mat',
    'comparison\\diabetes_tested_positive_26_variant1_ODGrCR.mat',
    'comparison\\diabetes_tested_positive_26_variant1_ODIN.mat',
    'comparison\\diabetes_tested_positive_26_variant1_ROD.mat',
    'comparison\\diabetes_tested_positive_26_variant1_SEQ.mat',
    'comparison\\diabetes_tested_positive_26_variant1_WDOD.mat',

    'comparison\\ionosphere_b_24_variant1_COF.mat',
    'comparison\\ionosphere_b_24_variant1_COPOD.mat',
    'comparison\\ionosphere_b_24_variant1_DCROD.mat',
    'comparison\\ionosphere_b_24_variant1_DIS.mat',
    'comparison\\ionosphere_b_24_variant1_ECOD.mat',
    'comparison\\ionosphere_b_24_variant1_fastABOD.mat',
    'comparison\\ionosphere_b_24_variant1_GrC.mat',
    'comparison\\ionosphere_b_24_variant1_IE.mat',
    'comparison\\ionosphere_b_24_variant1_IForest.mat',
    'comparison\\ionosphere_b_24_variant1_INFLO.mat',
    'comparison\\ionosphere_b_24_variant1_kNN.mat',
    'comparison\\ionosphere_b_24_variant1_LDOF.mat',
    'comparison\\ionosphere_b_24_variant1_LOF.mat',
    'comparison\\ionosphere_b_24_variant1_LoOP.mat',
    'comparison\\ionosphere_b_24_variant1_ODGrCR.mat',
    'comparison\\ionosphere_b_24_variant1_ODIN.mat',
    'comparison\\ionosphere_b_24_variant1_ROD.mat',
    'comparison\\ionosphere_b_24_variant1_SEQ.mat',
    'comparison\\ionosphere_b_24_variant1_WDOD.mat',

    'comparison\\pageblocks_1_258_variant1_COF.mat',
    'comparison\\pageblocks_1_258_variant1_COPOD.mat',
    'comparison\\pageblocks_1_258_variant1_DCROD.mat',
    'comparison\\pageblocks_1_258_variant1_DIS.mat',
    'comparison\\pageblocks_1_258_variant1_ECOD.mat',
    'comparison\\pageblocks_1_258_variant1_fastABOD.mat',
    'comparison\\pageblocks_1_258_variant1_GrC.mat',
    'comparison\\pageblocks_1_258_variant1_IE.mat',
    'comparison\\pageblocks_1_258_variant1_IForest.mat',
    'comparison\\pageblocks_1_258_variant1_INFLO.mat',
    'comparison\\pageblocks_1_258_variant1_kNN.mat',
    'comparison\\pageblocks_1_258_variant1_LDOF.mat',
    'comparison\\pageblocks_1_258_variant1_LOF.mat',
    'comparison\\pageblocks_1_258_variant1_LoOP.mat',
    'comparison\\pageblocks_1_258_variant1_ODGrCR.mat',
    'comparison\\pageblocks_1_258_variant1_ODIN.mat',
    'comparison\\pageblocks_1_258_variant1_ROD.mat',
    'comparison\\pageblocks_1_258_variant1_SEQ.mat',
    'comparison\\pageblocks_1_258_variant1_WDOD.mat',

    'comparison\\pima_TRUE_55_variant1_COF.mat',
    'comparison\\pima_TRUE_55_variant1_COPOD.mat',
    'comparison\\pima_TRUE_55_variant1_DCROD.mat',
    'comparison\\pima_TRUE_55_variant1_DIS.mat',
    'comparison\\pima_TRUE_55_variant1_ECOD.mat',
    'comparison\\pima_TRUE_55_variant1_fastABOD.mat',
    'comparison\\pima_TRUE_55_variant1_GrC.mat',
    'comparison\\pima_TRUE_55_variant1_IE.mat',
    'comparison\\pima_TRUE_55_variant1_IForest.mat',
    'comparison\\pima_TRUE_55_variant1_INFLO.mat',
    'comparison\\pima_TRUE_55_variant1_kNN.mat',
    'comparison\\pima_TRUE_55_variant1_LDOF.mat',
    'comparison\\pima_TRUE_55_variant1_LOF.mat',
    'comparison\\pima_TRUE_55_variant1_LoOP.mat',
    'comparison\\pima_TRUE_55_variant1_ODGrCR.mat',
    'comparison\\pima_TRUE_55_variant1_ODIN.mat',
    'comparison\\pima_TRUE_55_variant1_ROD.mat',
    'comparison\\pima_TRUE_55_variant1_SEQ.mat',
    'comparison\\pima_TRUE_55_variant1_WDOD.mat',

    'comparison\\sonar_M_10_variant1_COF.mat',
    'comparison\\sonar_M_10_variant1_COPOD.mat',
    'comparison\\sonar_M_10_variant1_DCROD.mat',
    'comparison\\sonar_M_10_variant1_DIS.mat',
    'comparison\\sonar_M_10_variant1_ECOD.mat',
    'comparison\\sonar_M_10_variant1_fastABOD.mat',
    'comparison\\sonar_M_10_variant1_GrC.mat',
    'comparison\\sonar_M_10_variant1_IE.mat',
    'comparison\\sonar_M_10_variant1_IForest.mat',
    'comparison\\sonar_M_10_variant1_INFLO.mat',
    'comparison\\sonar_M_10_variant1_kNN.mat',
    'comparison\\sonar_M_10_variant1_LDOF.mat',
    'comparison\\sonar_M_10_variant1_LOF.mat',
    'comparison\\sonar_M_10_variant1_LoOP.mat',
    'comparison\\sonar_M_10_variant1_ODGrCR.mat',
    'comparison\\sonar_M_10_variant1_ODIN.mat',
    'comparison\\sonar_M_10_variant1_ROD.mat',
    'comparison\\sonar_M_10_variant1_SEQ.mat',
    'comparison\\sonar_M_10_variant1_WDOD.mat',

    'comparison\\wbc_malignant_39_variant1_COF.mat',
    'comparison\\wbc_malignant_39_variant1_COPOD.mat',
    'comparison\\wbc_malignant_39_variant1_DCROD.mat',
    'comparison\\wbc_malignant_39_variant1_DIS.mat',
    'comparison\\wbc_malignant_39_variant1_ECOD.mat',
    'comparison\\wbc_malignant_39_variant1_fastABOD.mat',
    'comparison\\wbc_malignant_39_variant1_GrC.mat',
    'comparison\\wbc_malignant_39_variant1_IE.mat',
    'comparison\\wbc_malignant_39_variant1_IForest.mat',
    'comparison\\wbc_malignant_39_variant1_INFLO.mat',
    'comparison\\wbc_malignant_39_variant1_kNN.mat',
    'comparison\\wbc_malignant_39_variant1_LDOF.mat',
    'comparison\\wbc_malignant_39_variant1_LOF.mat',
    'comparison\\wbc_malignant_39_variant1_LoOP.mat',
    'comparison\\wbc_malignant_39_variant1_ODGrCR.mat',
    'comparison\\wbc_malignant_39_variant1_ODIN.mat',
    'comparison\\wbc_malignant_39_variant1_ROD.mat',
    'comparison\\wbc_malignant_39_variant1_SEQ.mat',
    'comparison\\wbc_malignant_39_variant1_WDOD.mat',

    'comparison\\wdbc_M_39_variant1_COF.mat',
    'comparison\\wdbc_M_39_variant1_COPOD.mat',
    'comparison\\wdbc_M_39_variant1_DCROD.mat',
    'comparison\\wdbc_M_39_variant1_DIS.mat',
    'comparison\\wdbc_M_39_variant1_ECOD.mat',
    'comparison\\wdbc_M_39_variant1_fastABOD.mat',
    'comparison\\wdbc_M_39_variant1_GrC.mat',
    'comparison\\wdbc_M_39_variant1_IE.mat',
    'comparison\\wdbc_M_39_variant1_IForest.mat',
    'comparison\\wdbc_M_39_variant1_INFLO.mat',
    'comparison\\wdbc_M_39_variant1_kNN.mat',
    'comparison\\wdbc_M_39_variant1_LDOF.mat',
    'comparison\\wdbc_M_39_variant1_LOF.mat',
    'comparison\\wdbc_M_39_variant1_LoOP.mat',
    'comparison\\wdbc_M_39_variant1_ODGrCR.mat',
    'comparison\\wdbc_M_39_variant1_ODIN.mat',
    'comparison\\wdbc_M_39_variant1_ROD.mat',
    'comparison\\wdbc_M_39_variant1_SEQ.mat',
    'comparison\\wdbc_M_39_variant1_WDOD.mat',

    'comparison\\yeast_ERL_5_variant1_COF.mat',
    'comparison\\yeast_ERL_5_variant1_COPOD.mat',
    'comparison\\yeast_ERL_5_variant1_DCROD.mat',
    'comparison\\yeast_ERL_5_variant1_DIS.mat',
    'comparison\\yeast_ERL_5_variant1_ECOD.mat',
    'comparison\\yeast_ERL_5_variant1_fastABOD.mat',
    'comparison\\yeast_ERL_5_variant1_GrC.mat',
    'comparison\\yeast_ERL_5_variant1_IE.mat',
    'comparison\\yeast_ERL_5_variant1_IForest.mat',
    'comparison\\yeast_ERL_5_variant1_INFLO.mat',
    'comparison\\yeast_ERL_5_variant1_kNN.mat',
    'comparison\\yeast_ERL_5_variant1_LDOF.mat',
    'comparison\\yeast_ERL_5_variant1_LOF.mat',
    'comparison\\yeast_ERL_5_variant1_LoOP.mat',
    'comparison\\yeast_ERL_5_variant1_ODGrCR.mat',
    'comparison\\yeast_ERL_5_variant1_ODIN.mat',
    'comparison\\yeast_ERL_5_variant1_ROD.mat',
    'comparison\\yeast_ERL_5_variant1_SEQ.mat',
    'comparison\\yeast_ERL_5_variant1_WDOD.mat']